# Generated by Django 2.2 on 2022-10-22 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_advice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('allowed', models.BooleanField(default=0)),
                ('use', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_advice.Use')),
            ],
        ),
    ]
