# Generated by Django 4.1.2 on 2022-10-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_advice', '0002_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
    ]
