# Generated by Django 4.1.2 on 2022-10-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_advice', '0003_delete_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Use',
            new_name='Task',
        ),
    ]
