# Generated by Django 4.1.2 on 2022-10-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_advice', '0004_rename_use_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.FloatField(default=0),
        ),
    ]
